config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'splashpages#index'

  resources :contacts,  only: [:index, :new, :create, :destroy]
  # why does this mess things up
  resources :posts
  resources :sessions, only: [:new, :create]

  get 'contacts/destroy_all', to: 'contacts#destroy_all'

  get '/test', to: 'splashpages#test'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :body
  extend FriendlyId
  friendly_id  :slug

  default_scope { order(created_at: :desc)}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  def admin?
    self.role == 'admin'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all.order('created_at DESC')
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.save
    redirect_to root_path
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    redirect_to contacts_path
  end

  def destroy_all
    Contact.destroy_all
    redirect_to contacts_path
  end


  private

  def contact_params
    params.require(:contact).permit(:email, :body)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :admin, only: [:edit, :update, :new, :create]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.friendly.find(params[:id])
    @title = @post.title
    @image = @post.image
    @url = "https://www.cryptocurrencieschecker.com/posts/#{@post.slug}"
    @shortDescription = @post.short_description
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.create!(post_params)
    redirect_to post
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    post = Post.friendly.find(params[:id])
    post.update(post_params)
    redirect_to post
  end




  private

  def post_params
    params.require(:post).permit(:title, :body, :short_description, :image, :slug)
  end

  def admin
    unless current_user && current_user.admin?
      flash[:danger] = "How dare you use your guile tactics on us!"
      redirect_to '/posts'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @meta_tag= "noindex"
  end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to new_session_path
      flash[:alert] = "Oops.. Houston, we have a problem..."
    end
  end

  def destroy
    @meta_tag= "noindex"

    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/splashpages_controller.rb
class SplashpagesController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/splashpages_helper.rb
module SplashpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contacts/index.html.erb
<%= link_to 'Destroy All', contacts_destroy_all_path(),
            # method: :delete,
            data: { confirm: 'Are you sure?' } %>

<% @contacts.each do |contact| %>
  <p>
    <%= contact.created_at %>
  </p>
  <p>
    <%= contact.body %>
  </p>
  <p>
    <%= contact.email %>
  </p>
  <%= link_to 'Destroy', contact_path(contact),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
  <br>
<% end %>

app/views/contacts/new.html.erb
<%= form_for :contact, url: contacts_path do |f| %>
  <div id="contact">
    <div class="contact_form">
      <p>
        <%= f.label :email %><br>
        <%= f.text_field :email, class: "form-control" %>
      </p>

      <p id="contact-text">
        <%= f.label :body, "Message" %><br>
        <%= f.text_area :body, class: "form-control contact-form" %>
      </p>

      <p class="text-center">
        <%= f.submit "Contact Me", class: "btn btn-contact" %>
      </p>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="logo">
      <div class="logo-image"><a href="/"></a></div>
      <h1><a href="/">CryptocurrenciesChecker</a></h1>
  </div>
  <div class="nav">
    <div class="app_link">
      <a href="/">App</a>
    </div>
    <div class="blog">
      <a href="/posts">Blog</a>
    </div>
  </div>
  <hr>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (@title + " - Crypto Paper Wallets Checker" if @title) || "Crypto Paper Wallets Checker"  %> </title>
    <%= csp_meta_tag %>

    <%# stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <% if @title %>
    <script type="application/ld+json">
      {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": "<%= @title %>",
        "author": "The Crypto Enthusiast",
        <% unless @image.nil? || @image == '' %>
        "image": "https://www.cryptopaperwalletschecker.com<%= asset_pack_path 'media/images/' + @image %>",
        <% end %>
        "genre": "digital business",
        "datePublished": "<%= @publication_date %>",
        "dateModified": "<%= @date_modified %>",
        "publisher": {
          "@type": "Organization",
          "name": "Crypto Paper Wallets Checker",
        },
        "url": "<%= @url %>",
        "description": "<%= @shortDescription %>"
      }
    </script>
    <meta name="description" content="<%= @twitterDescription %>">
    <% else %>
    <script type="application/ld+json">
      {
        "@context": "http://schema.org",
        "@type": "WebPage",
        "name": "Crypto Paper Wallets Checker",
        "description": "A web and mobile app for safely and easily checking your paper wallet balance plus related articles on crypto currency."
      }
    </script>
    <meta name="description" content="A web and mobile app for safely and easily checking your paper wallet balance plus related articles on crypto currency.">
    <% end %>

    <script>
      // Check that service workers are supported
      if ('serviceWorker' in navigator) {
        // Use the window load event to keep the page load performant
        window.addEventListener('load', () => {
          navigator.serviceWorker.register('/service-worker.js');
        });
      }
    </script>

    <link rel="apple-touch-icon" sizes="180x180" href="/pwa-assets/icons/apple-icon-180.jpg">
    <link rel="apple-touch-icon" sizes="167x167" href="/pwa-assets/icons/apple-icon-167.jpg">
    <link rel="apple-touch-icon" sizes="152x152" href="/pwa-assets/icons/apple-icon-152.jpg">
    <link rel="apple-touch-icon" sizes="120x120" href="/pwa-assets/icons/apple-icon-120.jpg">

    <meta name="apple-mobile-web-app-capable" content="yes">

    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-2048-2732.jpg" media="(prefers-color-scheme: dark) and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-2732-2048.jpg" media="(prefers-color-scheme: dark) and (device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1668-2388.jpg" media="(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-2388-1668.jpg" media="(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1536-2048.jpg" media="(prefers-color-scheme: dark) and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-2048-1536.jpg" media="(prefers-color-scheme: dark) and (device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1668-2224.jpg" media="(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-2224-1668.jpg" media="(prefers-color-scheme: dark) and (device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1620-2160.jpg" media="(prefers-color-scheme: dark) and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-2160-1620.jpg" media="(prefers-color-scheme: dark) and (device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1242-2688.jpg" media="(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-2688-1242.jpg" media="(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1125-2436.jpg" media="(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-2436-1125.jpg" media="(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-828-1792.jpg" media="(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1792-828.jpg" media="(prefers-color-scheme: dark) and (device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1080-1920.jpg" media="(prefers-color-scheme: dark) and (device-width: 360px) and (device-height: 640px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1920-1080.jpg" media="(prefers-color-scheme: dark) and (device-width: 360px) and (device-height: 640px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-750-1334.jpg" media="(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1334-750.jpg" media="(prefers-color-scheme: dark) and (device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-640-1136.jpg" media="(prefers-color-scheme: dark) and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)">
    <link rel="apple-touch-startup-image" href="/pwa-assets/splash/apple-splash-dark-1136-640.jpg" media="(prefers-color-scheme: dark) and (device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)">

    <link rel="manifest" href="/manifest.webmanifest">
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>

    <%= form.label :short_description %>
    <%= form.text_field :short_description %>

    <%= form.label :image %>
    <%= form.text_field :image %>

    <%= form.label :slug %>
    <%= form.text_field :slug %>

    <div class="trix_field">
      <%= form.label :body %>
      <%= form.rich_text_area :body, class: "post_font trix-content" %>
    </div>

    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= stylesheet_pack_tag 'post_new', 'trix' %>
<%= javascript_pack_tag 'post_new', 'trix' %>

<%= render 'posts/form' %>

app/views/posts/index.html.erb
<%= stylesheet_pack_tag 'post', 'nonapp_header' %>
<%= javascript_pack_tag 'post', 'nonapp_header' %>

<%= render 'layouts/header' %>

<main class="posts">
    <% @posts.each do |post| %>
      <div class="post post_font">
        <%= link_to post do %>
          <h2 class="post_title title_font"><%= post.title %></h2>
          <% unless post.created_at.to_i == post.updated_at.to_i %>
            <div class="post_time_updated_index">
              <span class="created_at">Created:  <%= post.created_at.localtime.strftime('%B %-d, %Y') %></span>
              <span class="updated_at">Updated:  <%= post.updated_at.localtime.strftime('%B %-d, %Y') %></span>
            </div>
          <% else %>
            <div class="post_time_index">
              <span class="created_at">Created: <%= post.created_at.localtime.strftime('%B %-d, %Y') %></span>
            </div>
          <% end %>
          <hr>
          <% if post.image %>
            <p>
              <%= post.image %>
            </p>
          <% end %>
          <p>
            <%= post.short_description %>
          </p>
        <% end %>
      </div>
    <% end %>
</main>

app/views/posts/new.html.erb
<%= stylesheet_pack_tag 'post_new', 'trix' %>
<%= javascript_pack_tag 'post_new', 'trix' %>

<%= render 'posts/form' %>

app/views/posts/show.html.erb
<%= stylesheet_pack_tag 'post', 'nonapp_header' %>
<%= javascript_pack_tag 'post', 'nonapp_header' %>

<%= render 'layouts/header' %>

<main class="post_main">
  <div class="post_individual post_font">
    <h2 class="post__title title_font"><%= @title %></h2>
    <% unless @post.created_at.to_i == @post.updated_at.to_i %>
      <div class="post_time_updated">
        <span class="created_at">Created:  <%= @post.created_at.localtime.strftime('%B %-d, %Y') %></span>
        <span class="updated_at">Updated:  <%= @post.updated_at.localtime.strftime('%B %-d, %Y') %></span>
      </div>
    <% else %>
      <div class="post_time">
        <span class="created_at">Created: <%= @post.created_at.localtime.strftime('%B %-d, %Y') %></span>
      </div>
    <% end %>
    <% unless @image.nil? || @image == '' %>
      <span class="post-image"><%= image_pack_tag @image %></span>
    <% end %>
    <div class="trix-content post-content">
      <%= @post.body %>
    </div>
  </div>
</main>

app/views/splashpages/index.html.erb
<%= javascript_pack_tag 'app' %>
<%= stylesheet_pack_tag 'app' %>
<script src="./html5-qrcode.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Material+Icons&display=block" rel="stylesheet">

<div class="app">

  <header class="header">
    <div class="logo">
        <div class="logo-image"><a href="/"></a></div>
        <h1><a href="/">CryptocurrenciesChecker</a></h1>
    </div>
    <div class="nav">
      <div class="spreadsheet">
        <h4>Speadsheet</h4>
        <div class="csv__reader" data-controller="csv-reader">
          <button class="btns" data-action="click->csv-reader#inputCsv">Load</button>
          <input class="hidden" type="file" id="csvFileInput"
            data-target="csv-reader.input"
            data-action="change->csv-reader#handleFiles" accept=".csv">
        </div>
        <div class="csv__generator" data-controller="csv-generator">
          <a href="#" class="export" data-action="click->csv-generator#createCsv">
            <button class="btns">Export</button></a>
        </div>
        <input id="csv_generator_input" type="text" value="" placeholder="Spreadsheet Name">
      </div>
      <div class="blog">
        <a href="/posts">Blog</a>
      </div>
    </div>
    <hr>
  </header>

  <main class="main">
    <section class="dropdowns">
      <cpwc-crypto-dropdowns>
      </cpwc-crypto-dropdowns>
    </section>
    <section class="inputs">
      <cpwc-addresses>
      </cpwc-addresses>
    </section>
  </main>

  <div class="modal" data-controller="qrmodal" data-action="click->qrmodal#closeModal">
    <div class="modal-content">
      <qr-code format="svg"></qr-code>
      <h5></h5>
    </div>
  </div>

  <div class="camera-modal" data-controller="cameramodal" data-action="click->cameramodal#closeModal">
    <div class="camera-modal-content">
      <cpwc-qrreader data-target="cameramodal.scanner"></cpwc-qrreader>
    </div>
  </div>

  <div class="copy-modal">
    <span>Copied To Cliboard</span>
  </div>

  <footer class="app__footer">
    <hr>
    <div class="app__contact">
      <a href="contacts/new" class="btns">Contact</a>
    </div>
    <div id="app__donation">
      <span>Donations for Bitcoin Appreciated!</span>
      <span class="app__donation"
        data-controller="copyToClipboard"
        data-action="click->copyToClipboard#copy">1337ipJbP7U9mi9cdLngL3g5Napum7tWzM</span>
    </div>
  </footer>

</div>

app/views/splashpages/test.html.erb
<%= javascript_pack_tag 'test' %>
<%= stylesheet_pack_tag 'test' %>

<div class="camera-modal" data-controller="cameramodal">
  <cpwc-qrreader data-target="cameramodal.scanner"></cpwc-qrreader>
</div>

<cpwc-addresses></cpwc-addresses>

<div class="" id="canvas">
  <label>
      <input id="show-scan-region" type="checkbox">
      Show scan region
  </label>
</div>